argo-cd:
  fullnameOverride: argocd

  global:
    domain: argocd.local.dev

  configs:
    cm:
      application.instanceLabelKey: argocd.argoproj.io/instance
      resource.customizations.ignoreResourceUpdates.ConfigMap: |
        jqPathExpressions:
          - '.metadata.annotations."cluster-autoscaler.kubernetes.io/last-updated"'
          - '.metadata.annotations."control-plane.alpha.kubernetes.io/leader"'

    params:
      application.namespaces: platform

    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, argocd-admins, role:admin
        p, role:admin, applications, *, */*, allow
        p, role:admin, clusters, *, *, allow
        p, role:admin, repositories, *, *, allow
        p, role:admin, projects, *, *, allow

  server:
    replicas: 1
    ingress:
      enabled: false

  controller:
    replicas: 1

  repoServer:
    replicas: 1

  applicationSet:
    enabled: false

  notifications:
    enabled: false

  dex:
    enabled: false
