apiVersion: v2
name: platform-cert-manager
description: cert-manager wrapper for TLS automation
type: application
version: 0.1.0

dependencies:
  - name: cert-manager
    version: "v1.17.1"
    repository: https://charts.jetstack.io
